version: 2
jobs:
  build: &test
    docker:
      - image: circleci/python:3.6

    working_directory: ~/repo

    steps:
      - checkout:
          path: ~/repo/diasnolaborables

      - run:
          name: Instalar entorno de ejecución
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install invoke
            invoke clean build

      - run:
          name: Ejecutar los tests
          command: |
            . venv/bin/activate 
            invoke test
  
  test-3.7:
    <<: *test
    docker:
      - image: circleci/python:3.7

  test-3.8-desarrollo:
    <<: *test
    docker:
      - image: circleci/python:3.8.0b3